language: php
php:
  - 5.6
  - hhvm
  - 7.0
install:
  - composer update
  - composer require satooshi/php-coveralls
before_script:
  - mkdir -p build/logs
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
